routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Site\HomeController@index');

Route::prefix('painel')->group(function(){
    Route::get('/', 'Admin\HomeController@index')->name('admin');
    Route::get('login', 'Admin\Auth\LoginController@index')->name('login');
    Route::post('login', 'Admin\Auth\LoginController@authenticate');

    Route::get('register', 'Admin\Auth\RegisterController@index')->name('register');
    Route::post('register', 'Admin\Auth\RegisterController@register');

    Route::post('logout', 'Admin\Auth\LoginController@logout')->name('logout');

    Route::resource('users', 'Admin\UserController');
    Route::resource('pages', 'Admin\PageController');

    Route::get('profile', 'Admin\ProfileController@index')->name('profile');
    Route::put('profilesave', 'Admin\ProfileController@save')->name('profile.save');

    Route::get('settings', 'Admin\SettingsController@index')->name('settings');
    Route::put('settingssave', 'Admin\SettingsController@save')->name('settings.save');
});

Route::fallback('Site\PageController@index');

resources/views/admin/pages/create.blade.php
@extends('adminlte::page')

@section('title', 'Nova Página')
    
@section('content_header')
    <h1>Nova Página</h1>
    
@endsection

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                <h5>
                    <i class="icon fas fa-ban"></i>Ocorreu um erro</h5>
                @foreach ($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach

            </ul>
        </div>
    @endif

    <div class="card">
        <div class="card-body">
            <form method="post" action="{{route('pages.store')}}" class="form-horizontal">
                @csrf
                <div class="form-group row">
                    <label for="" class="col-sm-2 col-form-label">Título da Página</label>
                    <div class="col-sm-10">
                    <input type="text" name="title" value="{{old('title')}}" class="form-control @error('title') is-invalid @enderror">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="" class="col-sm-2 col-form-label">Corpo da Página</label>
                    <div class="col-sm-10">
                        <textarea name="body" rows="5" value="{{old('body')}}" class="form-control bodyfield"></textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <input type="submit" value="Criar" class="btn btn-success">
                    </div>
                </div>
            </form>
        </div>
    </div>

    {{-- Editor TinyMCE --}}
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: 'textarea.bodyfield',
            height: 300,
            menubar: false,
            plugins: [
                'link', 'table', 'image', 'autoresize', 'lists'
            ],
            toolbar: 'undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify | table | link image | bullist numlist',
            content_css:[
                '{{asset('assets/css/content.css')}}'
            ],
            images_upload_url: '{{route('imageupload')}}',
            images_upload_credentials: true,
            convert_urls:false
        });
    </script>

@endsection

resources/views/admin/pages/edit.blade.php
@extends('adminlte::page')

@section('title', 'Editar Página')
    
@section('content_header')
    <h1>Editar Página</h1>
    
@endsection

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                <h5>
                    <i class="icon fas fa-ban"></i>Ocorreu um erro</h5>
                @foreach ($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach

            </ul>
        </div>
    @endif

    <div class="card">
        <div class="card-body">
            <form method="post" action="{{route('pages.update', ['page'=>$page->id])}}" class="form-horizontal">
                @method('PUT')
                @csrf
                <div class="form-group row">
                    <label for="" class="col-sm-2 col-form-label">Título</label>
                    <div class="col-sm-10">
                    <input type="text" name="title" value="{{$page->title}}" class="form-control @error('title') is-invalid @enderror">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="" class="col-sm-2 col-form-label">Corpo da Página</label>
                    <div class="col-sm-10">
                        <textarea name="body" rows="5" class="form-control bodyfield">
                            {{$page->body}}
                        </textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <input type="submit" value="Salvar" class="btn btn-success">
                    </div>
                </div>
            </form>
        </div>
    </div>
    
    {{-- Editor TinyMCE --}}
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: 'textarea.bodyfield',
            height: 300,
            menubar: false,
            plugins: [
                'link', 'table', 'image', 'autoresize', 'lists'
            ],
            toolbar: 'undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify | table | link image | bullist numlist',
            content_css:[
                '{{asset('assets/css/content.css')}}'
            ],
            images_upload_url: '{{route('imageupload')}}',
            images_upload_credentials: true,
            convert_urls:false
        });
    </script>

@endsection

resources/views/admin/pages/index.blade.php
@extends('adminlte::page')

@section('title', 'Páginas')
    
@section('content_header')
    <h1>
        Meus Usuários
        <a href="{{route('pages.create')}}" class="btn btn-sm btn-success">Nova Página</a>
    </h1>
    
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Título</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($pages as $page)
                        <tr>
                            <td style="width: 50px;">{{$page->id}}</td>
                            <td style="width: 700px">{{$page->title}}</td>
                            <td>
                                <a href="" target="_blank" class="btn btn-sm btn-primary">Visualizar</a>
                                <a href="{{route('pages.edit', ['page'=>$page->id])}}" class="btn btn-sm btn-info">Editar</a>

                                <form class="d-inline" action="{{route('pages.destroy', ['page'=>$page->id])}}" method="post" onsubmit="return confirm('Tem certeza que deseja excluir página {{$page->title}}?')">
                                    @method('DELETE')
                                    @csrf
                                    <button class="btn btn-sm btn-danger">Excluir</button>
                                </form>

                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    {{$pages->links()}}

@endsection